name: Deploy to Lightsail (git-pull build)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout (for audit/log)
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.8.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: "Ensure known_hosts (optional: adds host key for valyte.xyz)"
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Run remote deploy script over SSH
        run: |
          ssh -o BatchMode=yes -o StrictHostKeyChecking=yes \
            -p "${{ secrets.SSH_PORT || '22' }}" \
            "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "bash -lc 'cd ${REMOTE_APP_DIR:-/home/deploy/quest-web-app} && ./deploy.sh'"
        env:
          REMOTE_APP_DIR: /home/deploy/quest-web-app
