name: Deploy to Lightsail (git-pull build)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Run deploy script on Lightsail
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT || '22' }}
        fingerprint: ${{ secrets.SSH_FINGERPRINT }}
        script: |
          cd /home/deploy/quest-web-app
          git pull 
          bash ./deploy.sh


